#!/bin/bash
### author: Rene Pecnik, Aug 09 


### this script runs the cases setup in vnv for verifying and validating JOE
### and sends an email notification to the addresses specified below: 

email= renep@stanford.edu 


###run the cases

cd $MUM_HOME/vnv/ringleb; ./run       # checks whether JOE converges 2nd order on successive refined meshes

cd $MUM_HOME/vnv/flatplate; ./run     # check the laminar and turbulent solutions on a flat plat (we could also check invariance!)







