#!/bin/bash
### author: Rene Pecnik, Aug 09 
    
    ### create Joe.in from template
    sed "/RESTART/ s/restart.in/restart.SA.in/" JoeTemplate.in > Joe.in
    ### run joe
    mpirun -np 8 ./joe 1 >dummy
    ### prepare files
    cat dummy | grep RESID | tail -1 >> RESID
    mv restart.out restart.SA.in
    echo "finshed SA run"
