#!/bin/bash
### author: Rene Pecnik, Aug 09 

    ### create Joe.in from template
    sed "/RESTART/ s/restart.in/restart.WX.in/" JoeTemplate.in > Joe.in
    ### run joe
    mpirun -np 8 ./joe 3 >dummy
    ### prepare files
    cat dummy | grep RESID | tail -1 >> RESID
    mv restart.out restart.WX.in
    echo "finshed WX run"
