#!/bin/bash
### author: Rene Pecnik, Aug 09 

rm wall*.dat mail.txt RESID Makefile

### first make joe
cp $MUM_HOME/makefiles/Makefile .
make joe

### then run joe
./runLam
./runSA
./runSST
./runWX

### make plot
gnuplot < gnuplotscript

### send plot via mail
cp README mail.txt
cat RESID >> mail.txt
cat $MUM_HOME/run_vnv | grep 'email=' | awk '{print $2}' | while read line ; do mutt -s "skin friction" -a skinfriction.png $line < mail.txt ;done

### clean up 
#rm Joe.in joe joe.o wall*.dat fluid* restart.out restart.0* dummy RESID mail.txt Makefile skinfriction.png



