#!/bin/bash
### author: Rene Pecnik, Aug 09 

    ### create Joe.in from template
    sed "/RESTART/ s/restart.in/restart.in/" JoeTemplate.in > Joe.in
    ### run joe
    mpirun -np 8 ./joe >dummy  
    ### prepare files
    cat dummy | grep RESID | tail -1 >> RESID
    mv restart.out restart.in
    echo "finshed laminar run"
