#!MC 1100
$!VarSet |MFBD| = '.'
$!EXPORTSETUP EXPORTFORMAT = PNG
$!EXPORTSETUP EXPORTREGION = ALLFRAMES
$!EXPORTSETUP IMAGEWIDTH = 700
$!EXPORTSETUP USESUPERSAMPLEANTIALIASING = YES
$!EXPORTSETUP EXPORTFNAME = './density.png'
$!EXPORT 
  EXPORTREGION = ALLFRAMES
$!RemoveVar |MFBD|

