#!MC 1100
$!VarSet |MFBD| = '.'
$!EXPORTSETUP EXPORTFORMAT = PNG
$!EXPORTSETUP EXPORTREGION = ALLFRAMES
$!EXPORTSETUP IMAGEWIDTH = 1200
$!EXPORTSETUP USESUPERSAMPLEANTIALIASING = YES
$!EXPORTSETUP EXPORTFNAME = './export.png'
$!EXPORT 
  EXPORTREGION = ALLFRAMES
$!RemoveVar |MFBD|

