#!/usr/bin/perl

# make a layout file with a name like movie.XXXXXX.lay
# Use: ./mypng layout_name first_index last_index index_increment

$layout_prefix = $ARGV[0];

$Finit = $ARGV[1];
$Ffinal = $ARGV[2];
$Fstep = $ARGV[3];

$F = $Finit;

while ($F <= $Ffinal) {
    $File = sprintf("%06d", $F);
    print "working of file: $File\n";
    $F = $F + $Fstep;
    `cat $layout_prefix.XXXXXX.lay | sed "s/XXXXXX/$File/g" > $layout_prefix.tmp.lay`;
    `tec360 -mesa -b /home/terrapon/bin/png.mcr $layout_prefix.tmp.lay`;
    `mv export.png $layout_prefix.$File.png`;
#    `rm $layout_prefix.tmp.lay`;
}



